"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mago_1 = require("./mago");
var caballero_1 = require("./caballero");
var verdugo_1 = require("./verdugo");
var ladydi_1 = require("./ladydi");
var Juego_1 = require("./Juego");
var magoMejorado_1 = require("./magoMejorado");
var juego = new Juego_1.Juego();
var mago = new mago_1.Mago("Gandalf", 1, "Hechizos", 100, 5, 30, "convertir en sapo");
var caballero = new caballero_1.Caballero("Conan", 1, "Fuerza Física", 100, 10, 20, "Escudo Potente");
var verdugo = new verdugo_1.Verdugo("Legolas", 1, "Tortura", 100, 5, 40, "hacha de verdugo");
var ladydi = new ladydi_1.Ladydi("Diana", 1, "Voz Destructiva", 100, 7, 25, "baile de lucha");
var magoMejorado = new magoMejorado_1.MagoMejorado("Gandalf", 1, "Hechizos con los cuatro elementos", 100, 4, 50, "Magia con los cuatro elementos:Agua-Fuego-Aire-Tierra");
juego.agregarPersonaje(caballero);
juego.agregarPersonaje(mago);
juego.agregarPersonaje(verdugo);
juego.agregarPersonaje(ladydi);
juego.agregarPersonaje(magoMejorado);
juego.iniciarJuego();
console.log("El Caballero está preparado para atacar\n");
console.log("El Caballero evolucionó");
console.log(caballero_1.Caballero);
caballero.setdefEescudo("escudo mágico");
caballero.setNivel(2);
console.log(caballero_1.Caballero);
console.log("!Nivel y arma cambiado con exito¡\n");
magoMejorado.evolucionar();
console.log("El mago esta preparado para evolucionar a Mago Legendario");
console.log("El Mago evolucionó");
console.log(mago_1.Mago);
